<a href="https://colab.research.google.com/github/ja-yu/CS2020/blob/master/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]]) 
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [ ]:
ar2.ndim

2

In [ ]:
ar2.shape

(2, 3)

In [ ]:
ar=np.array([2,4,6,8])
ar.dtype

dtype('int64')

In [ ]:
ar=np.array([2,-1,6,3], dtype='float' )
ar

array([ 2., -1.,  6.,  3.])

In [ ]:
ar.dtype

dtype('float64')

In [ ]:
ar=np.array([2.,4,6,8])
ar.dtype

dtype('float64')

In [ ]:
f_ar = np.array([13,-3,8.88]) 
f_ar

array([13.  , -3.  ,  8.88])

In [ ]:
intf_ar=f_ar.astype(int) 
intf_ar

array([13, -3,  8])

In [ ]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [ ]:
x = np.zeros((2, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x = np.arange(2, 3, 0.1) 
x

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [13]:
np.linspace(1., 4., 6) 


array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [14]:
np.linspace(2.0, 3.0, num=5)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [15]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [16]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [17]:
import numpy as np
x = np.indices((3, 3))
x

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar10=np.diag((2,1,4,6))
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
a = np.array([0, 1, 2])  
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [20]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [33]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [30]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [31]:
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [34]:
x = np.arange(2,10).reshape(2,4) 
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [35]:
y = np.arange(2,10).reshape(4,2) 
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [36]:
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [37]:
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [39]:
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [40]:
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [42]:
ar.flatten()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [43]:
ar.transpose()

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [46]:
ar=np.array([14,15,16])
ar.shape
ar

array([14, 15, 16])

In [49]:
ar=ar[:, np.newaxis]
ar.shape 
ar

array([[[14]],

       [[15]],

       [[16]]])

In [50]:
x = np.arange(2,10) 
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x[0]

2

In [52]:
x[-2]

8

In [53]:
x[-1]

9

In [63]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])  
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [65]:
ar[1, 2]

7

In [56]:
ar[2,:]

array([11, 12, 13])

In [57]:
ar[:,1]

array([ 3,  8, 12])

In [58]:
ar[2, -1]

13

In [66]:
ar=2*np.arange(6) 
ar

array([ 0,  2,  4,  6,  8, 10])

In [70]:
print(ar[1:5:2])
print(ar[1:6:2])
print(ar[:4])
print(ar[4:])
print(ar[::3])

[2 6]
[ 2  6 10]
[0 2 4 6]
[ 8 10]
[0 6]


In [71]:
ar[:3]=1
ar 

array([ 1,  1,  1,  6,  8, 10])

In [78]:
ar=2*np.arange(6)
ar[2:]=np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

In [80]:
arr = np.empty((8, 4)) 
for i in range(8):     
 arr[i] = i 
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [81]:
ar=np.arange(1,5) 
ar.prod()

24

In [82]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [83]:
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [86]:
np.prod(ar,axis=1)

array([120, 120])

In [87]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]) 
print(ar.sum()) 
print(ar.mean()) 
print(np.median(ar))

54
6.0
6.0


In [93]:
ar=range(1000) 
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 350 µs per loop


In [90]:
ar=np.arange(1000) 
%timeit ar**3

The slowest run took 63.76 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.38 µs per loop


In [94]:
import numpy as np 
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [96]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [99]:
2.71828182846**9

8103.083927600996

In [100]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [101]:
print(arr+arr)    
print(arr-arr)
print(arr*arr)
print(1/arr)
print(arr ** 0.5)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [107]:
ar=np.array([[5,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar*ar2

array([[10,  2],
       [ 2,  2]])

In [108]:
ar.dot(ar2, ar)

array([[12, 12],
       [ 4,  4]])