<a href="https://colab.research.google.com/github/ja-yu/CS2020/blob/master/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar2=np.array([[0,3,5],[2,8,7]]) 
ar2

array([[0, 3, 5],
       [2, 8, 7]])

In [ ]:
ar2.ndim

2

In [ ]:
ar2.shape

(2, 3)

In [ ]:
ar=np.array([2,4,6,8])
ar.dtype

dtype('int64')

In [ ]:
ar=np.array([2,-1,6,3], dtype='float' )
ar

array([ 2., -1.,  6.,  3.])

In [ ]:
ar.dtype

dtype('float64')

In [ ]:
ar=np.array([2.,4,6,8])
ar.dtype

dtype('float64')

In [ ]:
f_ar = np.array([13,-3,8.88]) 
f_ar

array([13.  , -3.  ,  8.88])

In [ ]:
intf_ar=f_ar.astype(int) 
intf_ar

array([13, -3,  8])

In [ ]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [ ]:
x = np.zeros((2, 3))
x

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
x = np.arange(2, 3, 0.1) 
x

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [ ]:
np.linspace(1., 4., 6) 


array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
np.linspace(2.0, 3.0, num=5)


array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [ ]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [ ]:
import numpy as np
x = np.indices((3, 3))
x

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

In [ ]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
ar10=np.diag((2,1,4,6))
ar10

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [ ]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
a = np.array([0, 1, 2])  
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [ ]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [ ]:
np.tile(a, (2, 1, 2))

array([[[0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2]]])

In [ ]:
np.tile(np.array([[1,2],[6,7]]),3)

array([[1, 2, 1, 2, 1, 2],
       [6, 7, 6, 7, 6, 7]])

In [ ]:
np.tile(np.array([[1,2],[6,7]]),(2,2))

array([[1, 2, 1, 2],
       [6, 7, 6, 7],
       [1, 2, 1, 2],
       [6, 7, 6, 7]])

In [ ]:
x = np.arange(2,10).reshape(2,4) 
x

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [ ]:
y = np.arange(2,10).reshape(4,2) 
y

array([[2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
ar=np.array([np.arange(1,6),np.arange(10,15)])
ar

array([[ 1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14]])

In [ ]:
ar.ravel()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [ ]:
ar.T

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [ ]:
ar.T.ravel()

array([ 1, 10,  2, 11,  3, 12,  4, 13,  5, 14])

In [ ]:
ar.flatten()

array([ 1,  2,  3,  4,  5, 10, 11, 12, 13, 14])

In [ ]:
ar.transpose()

array([[ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 4, 13],
       [ 5, 14]])

In [ ]:
ar=np.array([14,15,16])
ar.shape
ar

array([14, 15, 16])

In [ ]:
ar=ar[:, np.newaxis]
ar.shape 
ar

array([[[14]],

       [[15]],

       [[16]]])

In [ ]:
x = np.arange(2,10) 
x

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x[0]

2

In [ ]:
x[-2]

8

In [ ]:
x[-1]

9

In [ ]:
ar = np.array([[2,3,4],[9,8,7],[11,12,13]])  
ar

array([[ 2,  3,  4],
       [ 9,  8,  7],
       [11, 12, 13]])

In [ ]:
ar[1, 2]

7

In [ ]:
ar[2,:]

array([11, 12, 13])

In [ ]:
ar[:,1]

array([ 3,  8, 12])

In [ ]:
ar[2, -1]

13

In [ ]:
ar=2*np.arange(6) 
ar

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
print(ar[1:5:2])
print(ar[1:6:2])
print(ar[:4])
print(ar[4:])
print(ar[::3])

[2 6]
[ 2  6 10]
[0 2 4 6]
[ 8 10]
[0 6]


In [ ]:
ar[:3]=1
ar 

array([ 1,  1,  1,  6,  8, 10])

In [ ]:
ar=2*np.arange(6)
ar[2:]=np.ones(4)
ar

array([0, 2, 1, 1, 1, 1])

In [ ]:
arr = np.empty((8, 4)) 
for i in range(8):     
 arr[i] = i 
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [ ]:
ar=np.arange(1,5) 
ar.prod()

24

In [ ]:
ar=np.array([np.arange(1,6),np.arange(1,6)])
ar

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
np.prod(ar,axis=0)

array([ 1,  4,  9, 16, 25])

In [ ]:
np.prod(ar,axis=1)

array([120, 120])

In [ ]:
ar=np.array([[2,3,4],[5,6,7],[8,9,10]]) 
print(ar.sum()) 
print(ar.mean()) 
print(np.median(ar))

54
6.0
6.0


In [ ]:
ar=range(1000) 
%timeit [ar[i]**3 for i in ar]

1000 loops, best of 3: 350 µs per loop


In [ ]:
ar=np.arange(1000) 
%timeit ar**3

The slowest run took 63.76 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.38 µs per loop


In [ ]:
import numpy as np 
arr = np.arange(10) 
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [ ]:
2.71828182846**9

8103.083927600996

In [ ]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
print(arr+arr)    
print(arr-arr)
print(arr*arr)
print(1/arr)
print(arr ** 0.5)

[[ 2.  4.  6.]
 [ 8. 10. 12.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[ 1.  4.  9.]
 [16. 25. 36.]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [ ]:
ar=np.array([[5,1],[1,1]])
ar2=np.array([[2,2],[2,2]])
ar*ar2

array([[10,  2],
       [ 2,  2]])

In [ ]:
ar.dot(ar2, ar)

array([[12, 12],
       [ 4,  4]])

In [8]:
import numpy as np
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5]) 
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5]) 
cond = np.array([True, False, True, True, False])
result = [(x if c else y)       
    for x, y, c in zip(xarr, yarr, cond)]  
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [9]:
result = np.where(cond, xarr, yarr) 
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [10]:
x1 = np.arange(9.0).reshape((3, 3)) 
x2 = np.arange(3.0) 
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

In [13]:
np.ones((3, 3))+np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [15]:
np.arange(3).reshape((3, 1))+np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [26]:
import numpy as np 
np.random.seed(0) 

x1 = np.random.randint(10, size=6)  
x2 = np.random.randint(10, size=(3, 4))  
x3 = np.random.randint(10, size=(3, 4, 5))  
print(x1)
print(x2)
print(x3)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [27]:
np.random.randint(1,size=5)

array([0, 0, 0, 0, 0])

In [31]:
np.random.randint(1,5)           

4

In [38]:
np.random.randint(-5,5,size=(2,2))

array([[ 2,  0],
       [ 4, -5]])

In [41]:
np.random.rand(4,2)

array([[0.92115761, 0.08311249],
       [0.27771856, 0.0093567 ],
       [0.84234208, 0.64717414],
       [0.84138612, 0.26473016]])

In [42]:
np.random.seed(0) 
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [43]:
np.random.seed(1676) 
np.random.rand(5)

array([0.39983389, 0.29426895, 0.89541728, 0.71807369, 0.3531823 ])

In [44]:
import numpy as np 
np.convolve([1, 2, 3], [0, 1, 0.5])

array([0. , 1. , 2.5, 4. , 1.5])

In [45]:
np.convolve([1, 2, 3], [0, 1, 0.5], 'same')

array([1. , 2.5, 4. ])

In [48]:
np.convolve([1, 2, 3], [0, 1, 0.5], 'valid')

array([2.5])

In [49]:
x = np.arange(10)
np.save('my_array', x)

In [50]:
np.load('my_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
aData = [1,2,3,4,5,6]
bData = [7,8,9,10,11,12]
np.savez('my_archive.npz', a=aData, b=bData)

In [53]:
myArch = np.load('my_archive.npz')
myArch['b']

array([ 7,  8,  9, 10, 11, 12])

In [54]:
myArch['a']

array([1, 2, 3, 4, 5, 6])

In [55]:
!cat my_txt.txt

cat: my_txt.txt: No such file or directory


In [72]:
ar=np.array([[3,2],[10,-1]]) 
ar 

array([[ 3,  2],
       [10, -1]])

In [73]:
ar.sort(axis=1) 
ar

array([[ 2,  3],
       [-1, 10]])

In [74]:
ar=np.array([[3,2],[10,-1]]) 
ar 

array([[ 3,  2],
       [10, -1]])

In [75]:
ar.sort(axis=0) 
ar

array([[ 3, -1],
       [10,  2]])

In [76]:
ar=np.arange(5)  
ar[::-1]

array([4, 3, 2, 1, 0])