<a href="https://colab.research.google.com/github/ja-yu/CS2020/blob/master/20201007.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
s = np.random.uniform(0, 1, 10)
s

array([0.13820033, 0.03768797, 0.27201415, 0.92914303, 0.68286545,
       0.73801032, 0.25366936, 0.51824916, 0.15436973, 0.29181415])

In [6]:
sum(s)

4.016023638631091

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.ones(10)*10

array([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])

In [9]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
a = np.array([[123], [456]])
a.ndim

2

In [12]:
a = np.diag((2, 1, 4, 6))
a

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

In [14]:
ar = np.array([2,4,6,8]); 
ar.dtype

dtype('int64')

In [15]:
import numpy as np
ar9 = np.eye(3);
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
ar9 = np.eye(3)
ar9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.array()